### ISSUE TITLE
Hunt the flaky - Tracking Tracking pages Codes

### ISSUE THREAD

**Issue by voodoorai2000** [AyuntamientoMadrid/consul#1175]
What
===
- Fix flaky spec
`rspec ./spec/features/tracks_spec.rb:304 # Tracking Tracking pages Codes`

```
Failures:
 1) Tracking Tracking pages Codes
     Failure/Error: visit "proposals"
     Capybara::Poltergeist::JavascriptError:
       One or more errors were raised in the Javascript code on the page. If you don't care about these errors, you can ignore them by setting js_errors: false in your Poltergeist configuration (see documentation for details).
       Error: [CKEDITOR.resourceManager.load] Resource name "default" was not found at "http://127.0.0.1:35005/assets/ckeditor/styles.js?t=H5SC".
       Error: [CKEDITOR.resourceManager.load] Resource name "default" was not found at "http://127.0.0.1:35005/assets/ckeditor/styles.js?t=H5SC".
           at http://127.0.0.1:35005/assets/application-fa4611dc628b0c29f0fdddfdae0112453b613257f5e664b67b044bd5a64308ee.js:32381
```

How
===
- [ ] Explain why the spec was flaky, or under which conditions/scenario it failed randomly
- [ ] Explain why your PR fixes it
- [ ] Backport to Upstream

Tips
===
- Run multiple times a single spec from the command line:
```
for run in {1..10}
do
  rspec ./spec/features/comments/topics_spec.rb:513
done
```

- Running a single spec in Travis:
Add option `:focus` to the spec and push your branch to Github, for example:
`scenario 'Show', :focus do`

- Running specs in the order they failed
After executing rspec you can see the seed used, add it as an option to rspec, for example
`rspec --seed 55638` 

Other things to watch out for
- Random generated values in the code that it’s covering
- Time related issues (current time or two time comparisons)

- More general tips:
https://semaphoreci.com/community/tutorials/how-to-deal-with-and-eliminate-flaky-tests

**Comment by iagirre** [comment]
I'm on it.

**Comment by raul-fuentes** [comment]
as @aitbw commented [here](https://github.com/AyuntamientoMadrid/consul/pull/1323#issuecomment-403895915)  this backport  isn't needed
