### ISSUE TITLE
Budgets 2.0

### ISSUE THREAD

**Issue by voodoorai2000** [AyuntamientoMadrid/consul#506]
Fase de Votación

- [x] Preparar Beta Testing (PR https://github.com/AyuntamientoMadrid/consul/pull/767)
- [x] Solo los admins pueden seguir evaluando (PR https://github.com/AyuntamientoMadrid/consul/pull/771)
- [x] Actualizar home para esta fase (PR https://github.com/AyuntamientoMadrid/consul/pull/772)
- [x] Actualizar la fase actual en la home de presupuestos (PR https://github.com/AyuntamientoMadrid/consul/pull/772)
- [x] Add phase to recommendation to differentiate between support and ballot phases (PR #770)
- [x] Deshabilitar Beta Testing antes del 15 de Mayo (PR https://github.com/AyuntamientoMadrid/consul/pull/775)
- [x] Asegurarse que todos los proyectos inviables tienen una explicación de inviabilidad
- [x] Guardar en DB el distrito donde se ha votado (tener en cuenta posible reclasificación) (PR https://github.com/AyuntamientoMadrid/consul/pull/779)
- [x] Guardar en local reclasificaciones previas y dejarlo en blanco en producción

Fase de Evaluación

- [x] Mostrar link a sección de evaluación (PR https://github.com/consul/consul/pull/1463)
- [x] Mostrar sólo algunas propuestas a los evaluadores (PR https://github.com/AyuntamientoMadrid/consul/pull/733)
- [x] Asegurarse que se ha de añadir una explicación para marcar como inviable
- [x] Mostrar los campos correspondientes al estado de la evaluación
- [x] Añadir validaciones para campos obligatorios (PR https://github.com/consul/consul/pull/1470)
- [x] Hojas de firmas (https://github.com/consul/consul/pull/1482)
- [x] Nota de corte (#745)
- [x] Mejorar la interfaz para mostrarle propuestas a los evaluadores (https://github.com/AyuntamientoMadrid/consul/pull/749)
- [x] Sólo mostrar el coste y su informe en la fase de votación (https://github.com/consul/consul/pull/1492)
- [ ] Restructurar los filtros en el índice de inversiones en admin
- [ ] Arreglar el tema de reclasificacion en Consul y comunicárselo a los forks

Cierre fase de Apoyos:

- [x] Confirmar que no se puede apoyar
- [x] Mostrar el número de apoyos en el show de una propuesta (PR https://github.com/consul/consul/pull/1462)
- [x] Actualizar botón en la home (https://github.com/AyuntamientoMadrid/consul/pull/732)
- [x] Confirmar que el texto del botón en la landing es correcto
- [x] No mostrar la cajita verde para votar en ciudad/distrito (https://github.com/AyuntamientoMadrid/consul/pull/732)

Fase de Apoyos:

Para lanzar:
- [x] Actualizar el texto del email de inviables
- [x] Delegación del voto
- [x] Estando en las propuestas de un distrito, al hacer click en una propuesta y darle a volver, debería lleva a las propuestas de distrito, ahora se muestra todas las propuestas
- [x] Quitar el popup en las propuestas para toda la ciudad
- [x] Arreglar css para que no se vean en gris los botones
- [x] En la landing cambiar el texto del botón principal a "Apoyar proyectos" 
- [x] En la home actualizar el texto a "Apoya proyectos para los 100 millones de euros de presupuestos participativos. Tú decides cómo gastarlos." "Apoyar proyectos"
- [x] Actualizar texto del email de propuestas inviables
- [x] Mostar link "Añadir proyectos de gasto a mi lista" sólo cuando el user está logueado
- [x] Actualizar home

Siguiente:
- [x] Mantener orden al darle a volver desde la vista individual de una propuesta
 - [x] Estadísticas - gráfica número total de apoyantes por día (admin/stats/spending_proposals)
 - [x] Estadísticas - número de apoyos en cada geozona
- [x] En Producción con orden aleatorio no aparece que ya has votado por una propuesta (en Pre sí) (PR #704)
- [x] En la sección admin para editar propuestas añadir el campo de 'propuesto en nombre de' (PR #708)
- [x] Interfaz para añadir chapas a las propuestas de gasto (textarea con ids y input con texto para la chapa) (PR https://github.com/AyuntamientoMadrid/consul/pull/713)
- [x] En la sección admin para editar propuestas añadir el campo de 'etiquetas' de usuario (PR #710)
- [x] Algunos proyectos de ciudad muestran la alerta (https://decide.madrid.es/presupuestos/presupuestos-participativos-2017/proyecto/77)
- [x] Actualizar el grupo de una propuesta al actualizar la partida (PR https://github.com/consul/consul/pull/1447)
- [x] Sólo permitir a un usuario votar en el primer distrito, aunque cambie la clasificación de propuestas
- [x] Asegurarse que podemos usar las hojas de firma (PR https://github.com/consul/consul/pull/1482)
- [ ] Mostrar un tick verde en el distrito que has elegido
- [ ] Mostrar el distrito que has elegido en el mensaje "Sólo puedes apoyar propuestas en un distrito"
- [x] En los informes de las propuestas al elegir viable o inviable tienen que desaparecer los campos que ya no hay que rellenar
- [ ] Que desde admin puedan marcar proyetos de presupuestos participativos (a ser posible debate y propuestas) para que esos elementos puedan al menos tener un elemento de diseño distinto (por ejemplo chapa) filtrarse de manera distinta y que la forma de marcar se marquen muchos al mismo tiempo.
- [x] En los listados de proyectos en admin en el link del título de cada una de ellas añadir un `target="_blank"`

Fase de Aceptación:
- [x] Mostrar el formulario de creación de proyectos sin turbolinks (PR #507)
- [x] Quitar las tendencias de etiquetas, mantener las categorías (PR #508)
- [x] Añadir welcome y lincarla desde el menu principal (PR #510)
- [x] Sólo mostrar el botón de apoyar en la fase de selección
- [x] Permitir sólo votar en una partida por grupo
- [x] Arreglar los modelos conflictivos (ballots, ballot_lines)
- [x] Escribir tests para el email de gracias e inviable
- [x] Escribir estilos para el email de gracias e inviable
- [x] Lista de inviables
- [x] Renombrar las traducciones 'inversiones' a 'proyectos de gasto' (PR https://github.com/AyuntamientoMadrid/consul/pull/518)
- [x] Utilizar y arreglar tests para las urls a medida (PR https://github.com/AyuntamientoMadrid/consul/pull/520)
- [x] La welcome debería aparecer en '/budgets' (PR https://github.com/AyuntamientoMadrid/consul/pull/518)
- [x] Revisar copies y estilos en los emails de gracias e inviables (PR https://github.com/consul/consul/pull/1356)
- [x] En la vista individual de un budget, mostrar el mensaje de login(si estás identificado aparece el botón de apoyar) (hacer en Consul) (PR https://github.com/consul/consul/pull/1357)
- [x] Quitar el feature flag de los resultados y estadísticas de spending proposals para que se sigan viendo (PR https://github.com/AyuntamientoMadrid/consul/pull/519)
- [ ] En el link a volver de un grupo con una única partida, se debería ver el show de un presupuesto
- [x] Cambiar nombres de las fases a: (PR consul/consul#1460)
  - [x] Presentación de proyectos
  - [x] Revisión interna de proyectos
  - [x] Fase de apoyos
  - [x] Evaluación de proyectos
  - [x] Votación final
  - [x] Votación finalizada
  - [x] Resultados

Siguiente:
- [x] Que en la home haya un link de "Ver propuestas inviables" que te lleve a elegir entre partidas, y luego veas las de la partida elegida. Que no aparezcan en la barra lateral.
- [x] Añadir settings en la consola:
  - [x] Setting['feature.budgets'] = true
  - [x] Setting['feature.spending_proposals'] = nil 
  - [x] Setting['min_age_to_participate'] = 16 (Y luego bajarla a 0 en el admin para que lo menores puedan proponer cosas)
- [x] En la vista de un grupo, quitar/arreglar el highlight en el distrito 
- [ ] Revisar specs pendinetes
   - [x] features/spending_proposals_spec.rb
   - [ ] features/users_spec.rb
   - [ ] features/votes_spec.rb:575 #Disable voting on spending proposals
   - [ ] features/ballots_spec.rb:440 # Ballots Permissions User is organization
   - [ ] features/budgets/ballots_spec.rb:504 # Ballots Permissions Insufficient funds (added after create)
- [x] Revisar traducciones no utilizadas(ver comentarios en i18n-tasks.yml)

Notas Despliegue a Producción:
- [x] Setting['feature.budgets'] = true
- [x] Setting['feature.spending_proposals'] = nil 
- [ ] Eliminar todas las settings de subfeatures de spending_proposals.
- [x] Setting['min_age_to_participate'] = 16 (Y luego bajarla a 0 en el admin para que los menores puedan proponer cosas)

**Comment by voodoorai2000** [comment]
Done or has been split into smaller issues
