### ISSUE TITLE
Votación

### ISSUE THREAD

**Issue by voodoorai2000** [AyuntamientoMadrid/consul#541]
Resultados/Estadísticas:

- [x] Generar los voter_hashes para Nvotes (PR https://github.com/AyuntamientoMadrid/consul/pull/657)
- [x] En estadísticas, total de votos, incluir los blancos y nulos, no sólo válidos
- [x] Mostrar resultados de las votación que se hizo por correo (PR https://github.com/AyuntamientoMadrid/consul/pull/658)
- [x] Calcular los datos demográficos de participación (PR https://github.com/AyuntamientoMadrid/consul/pull/666)
- [x] Añadir origen al Recuento Final
- [x] Urna para Nvotes (PR https://github.com/AyuntamientoMadrid/consul/pull/667)
- [x] Urna por correo (PR https://github.com/AyuntamientoMadrid/consul/pull/667)
- [x] Añadir porcentaje en las respuestas. x ej:  "Sí 20517 (80%)"
- [ ] Preparar setting para mostrar resultados
- [x] Número de participantes sin datos demográficos

**Para lanzar:**
- [x] Actualizar email de contacto en el iframe
- [x] Estadísticas de votos por urna y número de votantes (PR #614)
- [x] Optimizar rendimento de https://decide.madrid.es/questions/1
- [x] Informar al usuario de que le quedan más votaciones por votar (PR #612)
- [x] En officing mostrar sólo las propuesta que puede votar el usuario y están asignadas en esa urna
- [x] Revisar comportamiento al votar en tablet sin votaciones disponibles para ese usuario 
- [x] Si votas y le vuelves a dar a la votación sale un 404, porque ya no es votable, mejorar ux
- [x] Al confirmar voto en urna, mostrar un mensaje de error en lugar de una excepción si el usuario ya ha votado
- [ ] Soportar errores de timeout en el padrón (mostrar mensaje de error al usuario en lugar de generar una excepción)
- [x] Guardar el officer_assignment_id/booth_assignment_id en Voter para tener trazabilidad de qué poll_officer hace qué (PR #593)
- [x] Comprobar que la firma del callback de Ágora, viene de Ágora (PR https://github.com/AyuntamientoMadrid/consul/pull/594)
- [x] Mejorar rendimiento de la página de asignar urnas y presidentes (PR https://github.com/AyuntamientoMadrid/consul/pull/595)
- [x] Añadir booleano para definir si una mesa tiene urna física o se vota desde el tablet (PR https://github.com/AyuntamientoMadrid/consul/pull/596)
- [x] Asegurarnos que no se puede utilizar la funcionalidad de Poll::Answer (PR consul/consul#1415)

Seguridad:
- [x] Añadir claves ajenas para evitar duplicidades (PR https://github.com/consul/consul/pull/1414)
- [x] Escribir tests de integración para las diferentes combinaciones de poder o no poder votar (voto en urna, voto en tablet, voto en interfaz estándar) (PR https://github.com/AyuntamientoMadrid/consul/pull/597)
- [x] Testear permitir al usuario votar sólo una vez en Nvotes (PR https://github.com/AyuntamientoMadrid/consul/pull/597)

Front:
- [x] Quitar el link y pulir el texto que sale cuando no se carga el iframe (PR #601)
- [x] Añadir link en la web al status page de Nvotes (PR #607 )
- [x] Landing con links a votar (PR #601)

Puesta a punto producción:
- [x] Borrar datos de simulacros: Urnas, asignaciones, presidentes de mesa y voters
- [x] Volver a categorizar las propuestas por geozona, que lo quitamos para poder votar en todas las propuestas en el simulacro
- [x] Marcar las urnas que no tienen urna física
- [x] Copiar asignaciones de presidentes de otras votaciones
- [x] Cuando acabemos de asignar, cambiar la fecha de comienzo al 14. A las 8:30 cambiarlo al 13.

Estadísticas:
  - [x] Votos en Ágora (PR https://github.com/AyuntamientoMadrid/consul/pull/602)
  - [x] Votos en urnas físicas (PR https://github.com/AyuntamientoMadrid/consul/pull/602)

SEO:
  - [x] utilizar /votaciones en lugar de /polls (PR https://github.com/AyuntamientoMadrid/consul/pull/606)

Simulacro:

- [x] Pulir tsv para cargar las votaciones en Nvotes (PR https://github.com/AyuntamientoMadrid/consul/pull/561)
- [x] Apuntar al poll que toca en cada votación (PR https://github.com/AyuntamientoMadrid/consul/pull/567)
- [x] Mostrar iframes de las votaciones que puedo votar (interfaz tablet) (PR https://github.com/AyuntamientoMadrid/consul/pull/564)
- [x] Mostrar las votaciones que puedo y no puedo votar (interfaz estándar)
- [x] Permitir a los presidentes validar documentos en el Presimulacro (PR https://github.com/AyuntamientoMadrid/consul/pull/566)
- [x] Pulir los títulos y descripciones para las votaciones y preguntas (PR https://github.com/AyuntamientoMadrid/consul/pull/584)
- [x] Enviar a los usuarios a votar la siguiente votación donde puedan votar (interfaz tablet)

Despliegue a producción:
- [x] Mergear en master
- [x] Activar funcionalidad
- [x] Añadir secrets para nvotes
- [x] Ejecutar rake para crear votaciones
- [x] Actualizar `Setting['min_age_to_participate'] = 16`. Asegurarse de que `Setting['min_age_to_verify'] existe y vale `1`
- [x] Comprobar que funciona el callback de Nvotes

Presidentes de Mesa:
- [x] Verificación de DNI y fecha de nacimiento  (PR https://github.com/consul/consul/pull/1373)
- [x] Votación con tablet (PR https://github.com/AyuntamientoMadrid/consul/pull/551)
- [x] Interfaz de recuento final de votos por propuesta, y conteo de resultados. (PR https://github.com/consul/consul/pull/1376)
- [x] Importar preguntas (PR #548)

Usuarios:
- [x] Mostrar mapa de localización de las urnas
- [x] Revisar scope answerable_by (PR https://github.com/consul/consul/pull/1389)
- [x] Los menores no deberían poder votar (en tablet) (PR consul#1373)
- [x] Los menores no deberían poder votar (en la interfaz estándar)  (PR #570)

Admin:
- [x] Revisar que todo fluye creando la votación, preguntas, urnas y presidentes
- [x] Importación de datos
- [x] Recuentos y Resultados

Integración con AgoraVoting(Nvotes):
- [x] Integrar iframe (PR https://github.com/AyuntamientoMadrid/consul/pull/545)
- [x] Enviar voto encriptado (PR https://github.com/AyuntamientoMadrid/consul/pull/545)
- [x] tsv con información de las votaciones para Nvotes
- [x] Enviar a los usuarios a votar la siguiente votación donde puedan votar (tablet)
- [x] Integrar callback para saber quién ha votado (PR https://github.com/AyuntamientoMadrid/consul/pull/559)
- [x] Pensar si queremos mostrar el localizador del voto fuera del iframe. No
- [x] Mostrar el iframe en un layout a página completa en el tablet.

Ajustes:
- [x] A los menús de la interfaz del presidente les llamaría: "Validar documento y votar" "Recuento diario" "Recuento y escrutinio final"
- [x] Sólo hace falta introducir año de nacimiento, no día y fecha. Y si puede teclear en lugar de dropdown mejor, que será más rápido en la tablet. (PR https://github.com/consul/consul/pull/1382)
- [x] Tener en cuenta que el Padrón puede devolver la fecha de nacimiento en estos formatos: ddmmaaaa y aaaammdd, siempre 4 dígitos para el año) (PR #558)
- [x] Quitar las validaciones demográficas de un Poll::Voter (PR https://github.com/consul/consul/pull/1383)
- [x] Utilizar Poll.answerable_by(user) en lugar de Poll.incoming cuando esté arreglado answerable_by(user) (PR https://github.com/consul/consul/pull/1389)
- [x] Revisar el cálculo de le edad mínima (pr consul#1395)
- [x] Verificar que el presidente de mesa puede validar documentos ese día en esa urna (igual que en los recuentos) PR consul/consul#1392
- [x] Reasignarle los votos y demás objetos relacionados cuando un usuario borrado intenta verificar su cuenta. (PR consul/consul#1412)
- [x] El error que aparece cuando un menor intenta verificarse con un officer es confuso (PR consul/consul#1404)
- [x] Guarda llamadas al Padrón fallidas de un Presidente de mesa
- [x] Testear mostrar el iframe o las preguntas dependiendo de si puedes o no votar (interfaz estándar) (PR https://github.com/AyuntamientoMadrid/consul/pull/591)

**Nice to haves antes de lanzar:**

- [ ] Preguntar al Padrón si falta información demográfica del votante
- [ ] En Gestión, si falla el padrón que haya un botón "Saltar manualmente la comprobación de padrón"
- [x] Mejorar UX para enviar a los usuarios a votar la siguiente votación donde puedan votar (interfaz estándar)
- [ ] Parsear token de confirmación de voto en el callback de Nvotes para guardarlo en el Poll::Voter y mostrárselo a cada usuario en su actividad

**Después de lanzar:**

Recuentos:
- [x] Aunque no haya recuentos manuales deberían aparecer los "votos acumulados (automáticos)" de una votación
- [x] Añadir columna "Votos acumulados (automáticos)" en la pestaña recuentos de una votación
- [x] Añadir "votos acumulados (automáticos) totales" antes de tabla en la pestaña recuentos de una votación

Ajustes:
- [ ] Validación y recuento de votos por correo
- [x] Asegurarnos que no hay un presidente en dos urnas distintas en mismo día
- [ ] Rake para sacar los voter_hashes que podían votar en cada votación para el recuento
- [ ] Refactorizar polls show para cargar cada pestaña en una acción diferente
- [ ] Comprobar si podemos quitar el rol de officer, hasta dar de baja al usuario, y mantener todos los datos de votantes, turnos y recuentos
- [x] Usar un método de clase para la url del servidor nvotes y llamarlo nvotes_server_url
- [ ] Cambiar el atributo officing_voter de un usuario por una clase Officing::Voter
