### ISSUE TITLE
Admin sistemas tasks

### ISSUE THREAD

**Issue by bertocq** [AyuntamientoMadrid/consul#994]
# Worksop 1:. Administración de Sistemas.
- [ ] Get Docker windows install guides documented (find someone to try it)
- [ ] Document deployment steps to heroku used on our current demo environment at least for demoing purposes
- [ ] Document deployment to Cloud services (ICD17 are currently leading the effort, we should offer support and help with gathering/translating documentation
- [ ] Document configuration around email sending as much as possible https://github.com/consul/docs/issues/30
- [ ] Complete server requirements/configuration info with Madrid's examples if possible https://github.com/consul/docs/issues/25
- [ ] Document how to disable DelayedJobs if not needed or in trouble because of it https://github.com/consul/docs/issues/21 and if possible PR to disable it by default in consul (mega BONUS)
- [ ] Check https://github.com/consul/docs/issues/33 to see if its easily usable by other people and if so get it into the documentation? (BONUS)
